# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_listener:
    array_normalizer: fos_rest.normalizer.camel_keys
  routing_loader:
    default_format: json
    include_format: false
  view:
    view_response_listener: 'force'
    mime_types:
      json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1']
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors
  param_fetcher_listener: force
  #  exception:
  #    enabled: true
  #    exception_controller: 'App\Controller\ExceptionController::show'
  serializer:
    groups: ['Default']
  versioning:
    enabled: true
    default_version: '1.0'
    resolvers:
      query: false
      custom_header: true
      media_type:
        enabled: false
  format_listener:
    enabled: true
    rules:
      - { path: '^/api/doc', stop: true }
      - { path: '^/api/v1/mayday', priorities: ['json'], fallback_format: json }
      - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: true }