version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - ./.docker/conf/nginx/sites-available/mayday.highskills.local.conf:/etc/nginx/conf.d/mayday.highskills.local.conf
      - .:/var/www/html
    ports:
      - 80:80
    networks:
      - mayday_net
    depends_on:
      - php
      - db
  php:
    restart: always
    image: php:7.3-fpm-stretch
    ports:
      - 9000:9000
    build:
      context: ./.docker/conf/php-fpm
      dockerfile: 'Dockerfile'
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    environment:
      TZ: Europe/Moscow
    volumes:
      - .:/var/www/html
      - ./.docker/conf/php-fpm/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/conf/php-fpm/conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    working_dir: /var/www/html/sites/mayday/
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - mayday_net
  composer:
    image: composer
    volumes:
      - .:/app
    command: install
  db:
   image: mariadb
   environment:
     TZ: Europe/Moscow
     MYSQL_DATABASE: ${DB_NAME}
     MYSQL_USER: ${DB_USER}
     MYSQL_PASSWORD: ${DB_PASSWORD}
     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
   ports:
     - 3306:3306
   networks:
     - mayday_net
   restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - mayday_net

networks:
    mayday_net: